artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data
  source_url1: https://drive.google.com/uc?id=1J9khkxCng-rD4E8vtuJt8Ga1JnGgYuk-
  source_url2: https://drive.google.com/uc?id=15W2gIBC9KvNxOSNKPOsxB-9dn7FF9bQ- 
  local_generation_data: artifacts/data/generation.csv
  local_weather_data: artifacts/data/weather.csv
  
data_transformer:
  root_dir : artifacts/transformed_data
  transformed_data_path : artifacts/transformed_data/transormed_data.csv
  local_generation_data: artifacts/data/generation.csv
  local_weather_data: artifacts/data/weather.csv

model_trainer:
  root_dir: artifacts/model
  transformed_data_path : artifacts/transformed_data/transormed_data.csv
  saved_model_path : artifacts/model/trainedmodel.joblib







#https://drive.google.com/file/d/1J9khkxCng-rD4E8vtuJt8Ga1JnGgYuk-/view?usp=sharing

#https://drive.google.com/file/d/15W2gIBC9KvNxOSNKPOsxB-9dn7FF9bQ-/view?usp=drive_link