name: CI-CD


on: 
  push:
    branches:
      - main

jobs:
  sync_to_hub:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9.19]
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r req.txt



  push_to_hub:
    needs: sync_to_hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false
      - name: push to hub    
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI}}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        run: git push https://tmkartikey:$HF_TOKEN@huggingface.co/spaces/tmkartikey/solar_prediction main
  